# Common properties for both dev and prod.
version: '3.3'
services:
  web:
    build: ./react-apollo
    env_file: ./react-apollo/.env.local
    stdin_open: true
    ports:
      - 3000:3000

  graphql:
    build: ./node-graphql
    env_file: ./node-graphql/.env
    ports:
      - 5000:5000
